In [275]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
%config Completer.use_jedi = True
from sklearn.impute import SimpleImputer

In [276]:
# untouched_df = pd.read_excel('data.xlsx')

In [277]:
df = untouched_df

In [293]:
df.describe()

,Квартал договора,Квартал регистрации,Секция,Этаж,Площадь согласно ПД,Цена за кв. метр,Кол-во покупателей
count,64205.000000,64205.000000,64205.000000,64205.000000,64205.000000,63322.000000,64205.000000
mean,2.391122,2.363741,4.521424,8.175329,49.421023,147043.509746,1.250697
std,1.097174,1.078800,3.675298,4.843294,18.415195,37576.764737,0.601340
min,1.000000,1.000000,1.000000,1.000000,17.900000,0.000000,1.000000
25%,1.000000,1.000000,2.000000,4.000000,36.100000,121000.000000,1.000000
50%,2.000000,2.000000,4.000000,7.000000,45.300000,140607.470000,1.000000
75%,3.000000,3.000000,6.000000,11.000000,60.800000,169262.342500,1.000000
max,4.000000,4.000000,21.000000,25.000000,165.700000,356900.000000,18.000000

In [279]:
df = df.drop(['ID проекта', 'ID корпуса', 'Локация', 'ID лота', 'Расчетный бюджет объекта', 'Кол-во месяцев обременения', 'Рост бюджета покупки за период экспонирования', 'Округ', 'Месяц и год даты договора','Месяц и год даты регистрации'], axis=1)

In [280]:
df = df.rename(columns={'Количество комнат в прайс-листе, типология bnmap.pro': 'Количество комнат'})

In [292]:
df.head()

,Проект,Район,Адрес корпуса,Стадия строительной готовности на дату договора,Заявленный срок ввода в эксплуатацию,Старт продаж,Класс,Девелопер,Дата договора,Квартал договора,Дата регистрации,Квартал регистрации,Тип сделки,Тип объекта,Секция,Этаж,Количество комнат,Площадь согласно ПД,Цена за кв. метр,Метод определения цены,Включение скидок/акций в ценообразование,Скидки по дате договора,Отделка по корпусу,Тип продавца,Тип покупателя,Кол-во покупателей,Тип ипотеки,Участие объекта в оптовой сделке,"Срок в экспозиции до момента сделки, дней",Рост цены за 1 кв.м за период экспонирования
0,Баркли Медовая Долина,НАО,"Крекшино, д. 9 (3 оч.)",Строительство не начато,2020-06-30,2017-05-01,Комфорт,Barkli,2019-01-01,1,2019-02-18,1,Договор участия,квартира,4,5,студия,27.43,95325.34,Прайс совпадение площади,без скидки,Скидка 12% на ограниченный пул квартир. Скидка...,С отделкой,ЮЛ,ФЛ,1,Нет,Нет,н/д,н/д
1,Румянцево-Парк,НАО,"Московский п., в районе Румянцево дер., уч. 17...",Монтажные и отделочные работы,2020-06-30,2018-04-01,Комфорт,Lexion Development,2019-01-01,1,2019-05-08,2,Договор участия,квартира,4,11,2,62.60,114000.00,Прайс совпадение площади,без скидки,Скидка 2% при 100% оплате или ипотеке. При еди...,Без отделки,ЮЛ,ФЛ,1,Нет,Нет,211,"7,5%"
2,Румянцево-Парк,НАО,"Московский п., в районе Румянцево дер., уч. 17...",Монтажные и отделочные работы,2020-06-30,2018-04-01,Комфорт,Lexion Development,2019-01-01,1,2019-05-08,2,Договор участия,квартира,13,22,студия,24.10,143000.00,Прайс совпадение площади,без скидки,Скидка 2% при 100% оплате или ипотеке. При еди...,Без отделки,ЮЛ,ФЛ,3,Нет,Нет,211,"16,3%"
3,Баркли Медовая Долина,НАО,"Крекшино, д. 5 (2 оч.)",Монтажные и отделочные работы,2019-09-30,2016-08-01,Комфорт,Barkli,2019-01-02,1,2019-10-14,4,Договор уступки,квартира,4,6,студия,28.22,102625.78,Прайс совпадение площади,без скидки,Скидка 12% на ограниченный пул квартир. Скидка...,Без отделки,ЮЛ,ФЛ,1,Ипотека,Нет,н/д,н/д
4,Саларьево Парк,НАО,"Московский п., в районе дер. Саларьево, к. 15",Монтажные и отделочные работы,2020-03-31,2018-02-01,Комфорт,ПИК,2019-01-03,1,2019-02-13,1,Договор участия,квартира,1,21,2,51.20,131700.00,Прайс совпадение площади,без скидки,Скидка до 2% при 100% оплате или ипотеке (дейс...,С отделкой,ЮЛ,ФЛ,1,Нет,Нет,275,"15,0%"

In [282]:
def label_encode(name):
    df[name] = pd.Categorical(df[name])
    df[name] = df[name].cat.codes

In [283]:
df['Стадия строительной готовности на дату договора'].describe()

count                             64678
unique                                7
top       Монтажные и отделочные работы
freq                              35493
Name: Стадия строительной готовности на дату договора, dtype: object

In [284]:
df['Заявленный срок ввода в эксплуатацию'] = pd.to_datetime(df['Заявленный срок ввода в эксплуатацию'], errors='coerce')

In [285]:
df = df.drop('Год договора', axis=1)
df = df.drop('Год регистрации', axis=1)

In [286]:
def split_quater(name):
    quater,year = [],[]
    for i in df[name]:
        quater.append(i.split(' ')[0][0])
        year.append(i.split(' ')[-1])
    return quater, year

In [287]:
df.insert(9, "Квартал договора", split_quater('Квартал и год договора')[0])
df = df.drop('Квартал и год договора', axis=1)
df['Квартал договора'] = df['Квартал договора'].astype(str).astype(int)
df['Дата договора'] = pd.to_datetime(df['Дата договора'])

In [288]:
df.insert(12, "Квартал регистрации", split_quater('Квартал и год регистрации')[0])
df = df.drop('Квартал и год регистрации', axis=1)
df['Квартал регистрации'] = df['Квартал регистрации'].astype(str).astype(int)

In [289]:
df['Секция']=df['Секция'].replace(float('nan'),0)
imputer = SimpleImputer(missing_values=0, strategy='mean')
df['Секция'] = imputer.fit_transform(df['Секция'].values.reshape(-1, 1))
df['Секция'] = df['Секция'].astype(int)

In [290]:
# df = df[df['Цена за кв. метр'] != 0]

In [291]:
df['Количество комнат'] = df['Количество комнат'].replace('ст','студия')
df['Количество комнат'] = df['Количество комнат'].replace(float('nan'),0)
print(df['Количество комнат'].unique())
df = df[df['Количество комнат'] != 0]
df = df[df['Количество комнат'] != 'bez-tipa']
df = df[df['Количество комнат'] != '-']
print(df['Количество комнат'].unique())

['студия' '2' '1' '3' 0 '4' 'bez-tipa' '-']
['студия' '2' '1' '3' '4']

In [262]:
# df.to_excel('map.xlsx')

## Transforming for ML

In [272]:
df.head(5)

,Район,Стадия строительной готовности на дату договора,Заявленный срок ввода в эксплуатацию,Старт продаж,Класс,Девелопер,Дата договора,Квартал договора,Дата регистрации,Квартал регистрации,Тип сделки,Тип объекта,Секция,Этаж,Количество комнат,Площадь согласно ПД,Цена за кв. метр,Метод определения цены,Включение скидок/акций в ценообразование,Скидки по дате договора,Отделка по корпусу,Тип продавца,Тип покупателя,Кол-во покупателей,Тип ипотеки,Участие объекта в оптовой сделке,"Срок в экспозиции до момента сделки, дней",Рост цены за 1 кв.м за период экспонирования
0,0,6,2020-06-30,2017-05-01,2,0,2019-01-01,1,2019-02-18,1,1,1,4,5,0,27.43,95325.34,4,0,12,8,1,0,1,1,1,0,0.0
1,0,1,2020-06-30,2018-04-01,2,3,2019-01-01,1,2019-05-08,2,1,1,4,11,2,62.60,114000.00,4,0,2,0,1,0,1,1,1,211,7.5
2,0,1,2020-06-30,2018-04-01,2,3,2019-01-01,1,2019-05-08,2,1,1,13,22,0,24.10,143000.00,4,0,2,0,1,0,3,1,1,211,16.3
3,0,1,2019-09-30,2016-08-01,2,0,2019-01-02,1,2019-10-14,4,0,1,4,6,0,28.22,102625.78,4,0,12,0,1,0,1,0,1,0,0.0
4,0,1,2020-03-31,2018-02-01,2,17,2019-01-03,1,2019-02-13,1,1,1,1,21,2,51.20,131700.00,4,0,2,8,1,0,1,1,1,275,15.0

In [273]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64205 entries, 0 to 64677
Data columns (total 28 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Район                                            64205 non-null  int8
 1   Стадия строительной готовности на дату договора  64205 non-null  int8
 2   Заявленный срок ввода в эксплуатацию             63737 non-null  datetime64[ns]
 3   Старт продаж                                     64126 non-null  datetime64[ns]
 4   Класс                                            64205 non-null  int8
 5   Девелопер                                        64205 non-null  int8
 6   Дата договора                                    64205 non-null  datetime64[ns]
 7   Квартал договора                                 64205 non-null  int64
 8   Дата регистрации                                 64205 non-null  datetime64[ns]
 9   Квартал регистрации                              64205 non-null  int64
 10  Тип сделки                                       64205 non-null  int8
 11  Тип объекта                                      64205 non-null  int8
 12  Секция                                           64205 non-null  int64
 13  Этаж                                             64205 non-null  int64
 14  Количество комнат                                64205 non-null  object
 15  Площадь согласно ПД                              64205 non-null  float64
 16  Цена за кв. метр                                 63322 non-null  float64
 17  Метод определения цены                           64205 non-null  int8
 18  Включение скидок/акций в ценообразование         64205 non-null  int8
 19  Скидки по дате договора                          64205 non-null  int64
 20  Отделка по корпусу                               64205 non-null  int8
 21  Тип продавца                                     64205 non-null  int8
 22  Тип покупателя                                   64205 non-null  int8
 23  Кол-во покупателей                               64205 non-null  int64
 24  Тип ипотеки                                      64205 non-null  int8
 25  Участие объекта в оптовой сделке                 64205 non-null  int8
 26  Срок в экспозиции до момента сделки, дней        64205 non-null  int64
 27  Рост цены за 1 кв.м за период экспонирования     64205 non-null  float64
dtypes: datetime64[ns](4), float64(3), int64(7), int8(13), object(1)
memory usage: 8.6+ MB

In [265]:
label_encode('Район')
label_encode('Тип сделки')
label_encode('Тип объекта')
label_encode('Метод определения цены')
label_encode('Включение скидок/акций в ценообразование')
label_encode('Тип продавца')
label_encode('Тип покупателя')
label_encode('Тип ипотеки')
label_encode('Участие объекта в оптовой сделке')
label_encode('Стадия строительной готовности на дату договора')
label_encode('Класс')
label_encode('Девелопер')
label_encode('Отделка по корпусу')

In [266]:
df['Количество комнат'] = df['Количество комнат'].replace('студия',0)

In [267]:
df = df.drop('Проект', axis=1)
df = df.drop('Адрес корпуса', axis=1)

In [268]:
# max может влиять на модель, проверить с min
import re
c = 0
discounts = []
df['Скидки по дате договора'] = df['Скидки по дате договора'].replace(float('nan'),'')
for i in df['Скидки по дате договора']:
    found = "".join(re.findall(r'Скидка \d+%|Скидка до \d+%',i))
    if len(found) != 0:
        max_discount = max([int(i) for i in re.findall('[0-9]+',found)])
        discounts.append(max_discount)
    else:
        discounts.append(0)

In [269]:
df['Скидки по дате договора'] = discounts

In [270]:
# н/д в 0 может повлиять на модель!

df['Срок в экспозиции до момента сделки, дней'] = df['Срок в экспозиции до момента сделки, дней'].replace('н/д', 0)
df['Срок в экспозиции до момента сделки, дней'] = df['Срок в экспозиции до момента сделки, дней'].astype(str).astype(int)
df['Срок в экспозиции до момента сделки, дней'] = df['Срок в экспозиции до момента сделки, дней'].abs()

In [271]:
price = df['Рост цены за 1 кв.м за период экспонирования']
price = [float(i.split('%')[0].replace(',','.')) if '%' in i else i for i in price]
df['Рост цены за 1 кв.м за период экспонирования'] = price
df['Рост цены за 1 кв.м за период экспонирования'] = df['Рост цены за 1 кв.м за период экспонирования'].replace('н/д', 0)